### ISSUE TITLE
Location list doesn't appear by default on save

### ISSUE THREAD

**Issue by ljfranklin** [luan/vimfiles#108]
When saving a Go file containing a compilation error, the location list window no longer pops up. Looks like this was a side-effect of the switch between neomake and ale. Setting `let g:ale_open_list = 1` in `.vimrc` pops up the window on save as before. Was this an intentional change or should `let g:ale_open_list = 1` be added by default?

**Comment by luan** [comment]
This was intentional. You can see the errors with the gutter on the left and a summary at the bottom right. `W: 1 | E : 2` for errors and warnings. You can jump between them with Control-J (next error) and Control-K (previous error) for easier navigation.

If you want the old behavior you can do what you said, but in a local file not to clobber the config. Add `let g:ale_open_list = 1` to your `~/.vimrc.local` and you'll be fine.
