### ISSUE TITLE
Disabling auto-folding 

### ISSUE THREAD

**Issue by tscolari** [luan/vimfiles#148]
Hello, I'm having an issue that I'm failing to fix since I did an update.
Every time I open a large file (go tests for example) vim is folding everything automatically.

I've tried to set

```
set nofoldenable
set foldlevelstart=9999
```

on my vimrc.local but that got completely ignored.
Do you know what could be the cause? Or suggestions on how to avoid it?

**Comment by tscolari** [comment]
Jesus Christ, 
I'm closing this... it seems I've pressed some short cut that turned that behavior on - and persisted it even after closing vim. `zR` removed it... :/

**Comment by luan** [comment]
This config hasn't changed in a while so it's either something to do with a change in `vim-go` or this has always been a problem and you're just hitting it now (with this large file). I remember folding being a real pain in the past but I'm having a hard time recalling what I did to fix it.

Can you try this [new config](https://github.com/luan/nvim) (if you are on neovim)? I've been more actively maintaining it and hopefully, it won't have the issue. 

@totherme wrote a quick migration guide [here](https://github.com/luan/nvim/blob/master/doc/migrating-from-legacy.txt).

If that works, you can either 1) keep using the new config :) or 2) report back so we can try to figure out what the differences are.

If it doesn't work then maybe you can provide simple reproduction steps? I don't know if this file that's causing the problem is something you can share but if you can repro it on a large open-source project that would also be fine.

**Comment by tscolari** [comment]
It's quite weird, it started after the update. I might have pressed some key combination that triggered it too, but it seems to be persistent after exit. Typing `zR` seems to partially fix it, but it still a bit weird. Also the auto go imports stopped working, probably time to migrate to the new config you pointed!

I'm going to give it a try and see if I can survive with the new shortcuts haha
